export const featuredCreators = [
    {
        id: 1,
        name: "Manly BadAssHero",
        category: "Gaming",
        imageURL: "https://i.ytimg.com/vi/ndEw_q2OdPs/hqdefault.jpg",
        url: "https://youtube.com/c/manlybadasshero",
        instagram: "https://instagram.com/manlybadasshero",
        twitter: "https://twitter.com/manlybadasshero",
        youtube: "https://youtube.com/c/manlybadasshero",
        tiktok: "https://tiktok.com/@manlybadasshero",
        description: "A mysterious YouTuber known for diving deep into atmospheric indie horror games. Manly BadAssHero’s calm, methodical commentary and exceptional skill make for a captivating experience. His ability to blend storytelling with gameplay creates an immersive journey into eerie worlds, attracting a dedicated fanbase who crave suspense and chill."
    },
    {
        id: 2,
        name: "The Food Ranger",
        category: "Food",
        imageURL: "https://www.themanual.com/wp-content/uploads/sites/9/2024/01/Food-Ranger-noodles-1.jpg?resize=1200%2C630&p=1",
        url: "https://www.thefoodranger.com",
        instagram: "https://www.instagram.com/thefoodranger",
        twitter: "https://twitter.com/thefoodranger",
        youtube: "https://www.youtube.com/c/thefoodranger",
        tiktok: "https://www.tiktok.com/@thefoodranger",
        description: "Trevor James, aka The Food Ranger, embarks on a global culinary adventure exploring street foods, local markets, and hidden gems. With his energetic and curious approach, Trevor not only showcases delicious dishes but also uncovers the cultural stories behind the food, delivering rich, immersive travel and food experiences that inspire wanderlust and appetites alike."
    },
    {
        id: 3,
        name: "Bro Code",
        category: "Coding",
        imageURL: "https://yt3.googleusercontent.com/ytc/AIdro_mPFVsxROj1dOtTWc9iNBwDYV4z42Q8LPokBSewiW9pCSg=s900-c-k-c0x00ffffff-no-rj",
        url: "https://www.youtube.com/@BroCodez", 
        instagram: "https://www.instagram.com/brocodez/",
        twitter: "https://twitter.com/brocodez",
        youtube: "https://www.youtube.com/@BroCodez",
        tiktok: "",
        description: "Bro Code takes the mystery out of programming by delivering clear, engaging tutorials tailored for beginners and intermediate coders. Covering everything from web development basics to advanced frameworks, Bro Code emphasizes practical projects that help viewers build real skills and confidence, making software development accessible and fun."
    },
    {
        id: 4,
        name: "Bob Ross",
        category: "Art",
        imageURL: "https://i.ytimg.com/vi/OJ_xqtvZf3o/maxresdefault.jpg",
        url: "https://www.bobross.com",
        instagram: "https://www.instagram.com/bobross_thejoyofpainting/",
        twitter: "https://twitter.com/bobrossofficial",
        youtube: "https://www.youtube.com/@BobRossInc",
        tiktok: "https://www.tiktok.com/@bobross_official",
        description: "The late Bob Ross became an icon of soothing creativity with his gentle teaching style and instantly recognizable phrases. His series 'The Joy of Painting' introduced millions to the joy of art through easy-to-follow steps and his philosophy that everyone can create beauty, turning painting into a calming and uplifting experience."
    },
    {
        id: 5,
        name: "Dude Perfect",
        category: "Sports",
        imageURL: "https://www.tubefilter.com/wp-content/uploads/2019/11/dude-perfect-1280x720.jpg",
        url: "https://www.dudeperfect.com",
        instagram: "https://www.instagram.com/dudeperfect/",
        twitter: "https://twitter.com/DudePerfect",
        youtube: "https://www.youtube.com/@DudePerfect",
        tiktok: "https://www.tiktok.com/@dudeperfect",
        description: "Dude Perfect is a group of friends redefining the limits of trick shots, stunts, and sports entertainment. Their videos combine extreme skill, humor, and camaraderie, creating family-friendly content that celebrates teamwork and creativity. Their inventive challenges and jaw-dropping feats have earned them a global following."
    },
    {
        id: 6,
        name: "Kurzgesagt – In a Nutshell",
        category: "Education",
        imageURL: "https://i.ytimg.com/vi/JtUAAXe_0VI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBlJgAWiLAFiJUICBXbX8W_Yt6Efw",
        url: "https://kurzgesagt.org",
        instagram: "https://www.instagram.com/kurz_gesagt/",
        twitter: "https://twitter.com/Kurz_Gesagt",
        youtube: "https://www.youtube.com/@Kurzgesagt",
        tiktok: "https://www.tiktok.com/@kurz_gesagt",
        description: "Kurzgesagt translates complex scientific and philosophical topics into breathtaking animated videos. Their visually stunning narratives break down everything from the cosmos to human biology, sparking curiosity and providing clarity on subjects that often seem inaccessible, making learning a delight for audiences worldwide."
    },
    {
        id: 7,
        name: "Lilly Singh",
        category: "Comedy",
        imageURL: "https://media.vanityfair.com/photos/5d850d6bfb266600089efa17/16:9/w_2000,h_1125,c_limit/Lilly-Singh-late-night.jpg",
        url: "https://www.lillysingh.com",
        instagram: "https://www.instagram.com/lilly/",
        twitter: "https://twitter.com/Lilly",
        youtube: "https://www.youtube.com/@LillySingh",
        tiktok: "https://www.tiktok.com/@lilly",
        description: "Lilly Singh is a powerhouse of energy and laughter, blending sharp social commentary with infectious comedy. From viral sketches to hosting her own late-night talk show, she connects deeply with diverse audiences, using humor to address important issues while delivering relentless entertainment."
    },
    {
        id: 8,
        name: "Veritasium",
        category: "Science",
        imageURL: "https://i.ytimg.com/vi/S1tFT4smd6E/maxresdefault.jpg",
        url: "https://www.veritasium.com",
        instagram: "https://www.instagram.com/veritasium/",
        twitter: "https://twitter.com/veritasium",
        youtube: "https://www.youtube.com/@veritasium",
        tiktok: "https://www.tiktok.com/@veritasium",
        description: "Hosted by Derek Muller, Veritasium explores fascinating scientific phenomena and debunks misconceptions through engaging experiments and storytelling. The channel’s thoughtful approach encourages viewers to think critically about science, technology, and the nature of knowledge itself."
    },
    {
        id: 9,
        name: "Jenna Marbles",
        category: "Comedy",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStFgNNwRNEKGM0mE8X7lzxcargaRe-wcqGlg&s",
        url: "https://www.youtube.com/user/JennaMarbles",
        instagram: "https://www.instagram.com/jennamarbles/",
        twitter: "https://twitter.com/Jenna_Marbles",
        youtube: "https://www.youtube.com/user/JennaMarbles",
        tiktok: "",
        description: "Jenna Marbles was a beloved YouTube personality known for her relatable humor, quirky personality, and genuine connection with fans. Her videos, ranging from hilarious challenges to heartfelt moments with her pets, helped shape the early YouTube community with authenticity and warmth."
    },
    {
        id: 10,
        name: "Emma Chamberlain",
        category: "Lifestyle",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj-6P72RHi47K_0qWX8IlWmvURUtcOYnF2aA&s",
        url: "https://www.youtube.com/c/emmachamberlain",
        instagram: "https://www.instagram.com/emmachamberlain/",
        twitter: "https://twitter.com/emmachamberlain",
        youtube: "https://www.youtube.com/c/emmachamberlain",
        tiktok: "https://www.tiktok.com/@emmachamberlain",
        description: "Emma Chamberlain revolutionized vlogging with her candid, humorous, and unfiltered style. Her relatable content, quirky editing, and coffee-fueled adventures have resonated deeply with Gen Z audiences, influencing a generation of creators and redefining online authenticity."
    },
    {
        id: 11,
        name: "Philip DeFranco",
        category: "News",
        imageURL: "https://imageio.forbes.com/blogs-images/michaelhumphrey/files/2015/08/Phil-in-PDS.png?format=png&height=600&width=1200&fit=bounds",
        url: "https://www.youtube.com/user/sxephil",
        instagram: "https://www.instagram.com/phillydefranco/",
        twitter: "https://twitter.com/PhillyD",
        youtube: "https://www.youtube.com/user/sxephil",
        tiktok: "https://www.tiktok.com/@phillydefranco",
        description: "Philip DeFranco is a pioneering news commentator known for his fast-paced, honest, and insightful breakdowns of current events and internet culture. With a unique blend of humor and sincerity, he keeps audiences informed while encouraging critical thinking."
    },
    {
        id: 12,
        name: "Safiya Nygaard",
        category: "Beauty",
        imageURL: "https://yt3.googleusercontent.com/ytc/AIdro_kWVZIZfrF5u_NlubEAQgXoegyKOPih60YMyYxWtCGFkxo=s900-c-k-c0x00ffffff-no-rj",
        url: "https://www.youtube.com/c/safiyanygaard",
        instagram: "https://www.instagram.com/safiyany/",
        twitter: "https://twitter.com/safiyajn",
        youtube: "https://www.youtube.com/c/safiyanygaard",
        tiktok: "https://www.tiktok.com/@safiyany",
        description: "Safiya Nygaard blends beauty, fashion, and science to create fascinating content that explores trends, experiments, and personal style. Her thoughtful approach and curiosity have garnered a loyal audience eager for honest reviews and creative explorations."
    },
    {
        id: 13,
        name: "Linus Tech Tips",
        category: "Tech",
        imageURL: "https://helios-i.mashable.com/imagery/articles/072iBcNtaNWKVzEydNtsAol/hero-image.fill.size_1248x702.v1692285485.png",
        url: "https://www.youtube.com/user/LinusTechTips",
        instagram: "https://www.instagram.com/linustech/",
        twitter: "https://twitter.com/LinusTech",
        youtube: "https://www.youtube.com/user/LinusTechTips",
        tiktok: "https://www.tiktok.com/@linustech",
        description: "Linus Tech Tips is the go-to channel for in-depth hardware reviews, PC builds, and tech tutorials. Linus and his team deliver engaging content that balances technical depth with accessibility, empowering viewers to make informed decisions in the fast-evolving tech world."
    },
    {
        id: 14,
        name: "Jared Polin",
        category: "Photography",
        imageURL: "https://cdn.fstoppers.com/styles/large-16-9/s3/lead/2018/07/jared_polin_froknowsphoto_college_student_advice.jpg",
        url: "https://froknowsphoto.com/",
        instagram: "https://www.instagram.com/jaredpolin/",
        twitter: "https://twitter.com/FroKnowsPhoto",
        youtube: "https://www.youtube.com/user/JaredPolin",
        tiktok: "",
        description: "Jared Polin, known as FroKnowsPhoto, is a bold and outspoken photography expert. His videos range from camera reviews to tutorials and candid critiques, providing both entertainment and education to photographers of all skill levels looking to elevate their craft."
    },
    {
        id: 15,
        name: "Gordon Ramsay",
        category: "Cooking",
        imageURL: "https://assets.entrepreneur.com/images/misc/1698329669_GettyImages-1238151007.jpg?width=1000",
        url: "https://www.gordonramsay.com",
        instagram: "https://www.instagram.com/gordongram/",
        twitter: "https://twitter.com/GordonRamsay",
        youtube: "https://www.youtube.com/c/gordonramsay",
        tiktok: "https://www.tiktok.com/@gordonramsayofficial",
        description: "Gordon Ramsay, a world-renowned chef and TV personality, is famous for his fiery passion and high standards in the kitchen. His content ranges from intense culinary challenges to approachable home cooking tips, always delivered with his signature candid and no-nonsense style."
    },
    {
        id: 16,
        name: "Mr. Kate",
        category: "DIY",
        imageURL: "https://i.ytimg.com/vi/0dnWiQMSQoU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA0vTypPOPPFOML7TigANC75mmRBw",
        url: "https://mrkate.com",
        instagram: "https://www.instagram.com/mrkate/",
        twitter: "https://twitter.com/mrkate",
        youtube: "https://www.youtube.com/user/TheMrkate",
        tiktok: "https://www.tiktok.com/@mrkate",
        description: "Mr. Kate brings creativity and boldness to interior design and DIY projects. With transformative room makeovers and imaginative crafts, they inspire viewers to infuse personality and art into everyday living spaces, proving that design is for everyone."
    },
    {
        id: 17,
        name: "Casey Neistat",
        category: "Vlogging",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBNs87DgvEieaa4hN-wFkkAassoAoSfSm1Tw&s",
        description: "Casey Neistat is a pioneering vlogger whose cinematic style and authentic storytelling have influenced a generation. Whether showcasing life in NYC or sharing motivational insights, his dynamic videos blend artistry and raw emotion, making every upload a compelling visual journey."
    },
    {
        id: 18,
        name: "Marques Brownlee",
        category: "Tech",
        imageURL: "https://th.bing.com/th/id/R.bade44ca76b92c46118a4fe3a7263064?rik=j73MMwW7FGQbFg&pid=ImgRaw&r=0",
        url: "https://www.youtube.com/user/marquesbrownlee",
        instagram: "https://www.instagram.com/mkbhd/",
        twitter: "https://twitter.com/MKBHD",
        youtube: "https://www.youtube.com/user/marquesbrownlee",
        tiktok: "https://www.tiktok.com/@mkbhd",
        description: "Marques Brownlee (MKBHD) is a leading tech reviewer known for his crystal-clear videos on the latest gadgets, smartphones, and tech innovations. His thorough analysis and polished production set the standard for consumer technology content."
    },
    {
        id: 19,
        name: "NikkieTutorials",
        category: "Beauty",
        imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaoykTUBNOV5AbgCf2QWSYbqDK7snWEmoPP4mKUNUKTT7wpWmbrYhH69_vTUk8QlRO48ZoEL7ccmF5tIn5GPB_gw",
        url: "https://www.youtube.com/user/NikkieTutorials",
        instagram: "https://www.instagram.com/nikkietutorials/",
        twitter: "https://twitter.com/NikkieTutorials",
        youtube: "https://www.youtube.com/user/NikkieTutorials",
        tiktok: "https://www.tiktok.com/@nikkietutorials",
        description: "NikkieTutorials is a celebrated makeup artist and beauty influencer, known for her detailed tutorials and empowering messages. Her approachable style and emphasis on self-confidence have made her a beloved figure in the beauty community."
    },
    {
        id: 20,
        name: "Peter McKinnon",
        category: "Photography",
        imageURL: "https://i.ytimg.com/vi/iMHFLKc5AFE/hqdefault.jpg",
        url: "https://www.youtube.com/user/petermckinnon24",
        instagram: "https://www.instagram.com/petermckinnon/",
        twitter: "https://twitter.com/PeterMcKinnon",
        youtube: "https://www.youtube.com/user/petermckinnon24",
        tiktok: "https://www.tiktok.com/@petermckinnon",
        description: "Peter McKinnon combines photography, filmmaking, and storytelling with insightful tutorials and gear reviews. His energetic delivery and cinematic style inspire creators to elevate their craft and tell powerful stories visually."
    },

    {
    id: 21,
    name: "Liza Koshy",
    category: "Comedy",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJt7jPdrkMwo3fOLAFsnfkLdbd7kmUCJdy8w&s",
    url: "https://www.youtube.com/user/lizakoshy",
    instagram: "https://www.instagram.com/lizakoshy/",
    twitter: "https://twitter.com/LizaKoshy",
    youtube: "https://www.youtube.com/user/lizakoshy",
    tiktok: "https://www.tiktok.com/@lizakoshy",
    description: "Liza Koshy is a multitalented comedian, actress, and host who rose to fame with her high-energy Vine skits and continued her success on YouTube with relatable comedy, quirky characters, and sharp improv skills. Known for her expressive face and rapid-fire humor, Liza has also made a successful transition into mainstream entertainment while staying true to her internet roots. Her content combines creativity, confidence, and cultural relevance, making her a beloved figure across generations."
},
{
    id: 22,
    name: "Yoga With Adriene",
    category: "Fitness",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBGyMqXgWh_Y1C527TuKBVLmGaZ_z99tBArw&s",
    url: "https://www.youtube.com/user/yogawithadriene",
    instagram: "https://www.instagram.com/adrienelouise/",
    twitter: "",
    youtube: "https://www.youtube.com/user/yogawithadriene",
    tiktok: "",
    description: "Adriene Mishler, the calm and encouraging voice behind Yoga With Adriene, has created a global wellness community through her accessible, inclusive yoga videos. Her sessions range from beginner-friendly stretches to mindful flows, all designed to support both mental and physical well-being. With her signature tagline 'Find what feels good,' Adriene empowers millions to develop a sustainable, joyful yoga practice from home."
},
{
    id: 23,
    name: "Colin and Samir",
    category: "Content Creation",
    imageURL: "https://i.ytimg.com/vi/Yk4KG9Vc2Hs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBZYRx7jIp2wFVXvsqaLP82XCvjaA",
    url: "https://www.youtube.com/c/ColinandSamir",
    instagram: "https://www.instagram.com/colinandamir/",
    twitter: "https://twitter.com/ColinandSamir",
    youtube: "https://www.youtube.com/c/ColinandSamir",
    tiktok: "",
    description: "Colin and Samir are storytellers and creators who specialize in breaking down the creator economy. Through interviews, commentary, and in-depth videos, they spotlight the lives, struggles, and business models of YouTubers and influencers. Their content provides rare behind-the-scenes insight into digital storytelling, making them a valuable resource for aspiring creators and media professionals alike."
},
{
    id: 24,
    name: "Bon Appétit",
    category: "Food",
    imageURL: "https://cdn.prod.website-files.com/5e8f5614a438dde426002a6e/5ed4d49fef82ae2a3087a979_bon-appe%CC%81tit-youtube-channel-1.png",
    url: "https://www.youtube.com/c/BonAppetitDotCom",
    instagram: "https://www.instagram.com/bonappetitmag/",
    twitter: "https://twitter.com/BonAppetit",
    youtube: "https://www.youtube.com/c/BonAppetitDotCom",
    tiktok: "https://www.tiktok.com/@bonappetitmag",
    description: "Bon Appétit is more than just a cooking channel—it's a culinary playground featuring charismatic chefs, creative recipes, and food science explorations. From gourmet challenges to kitchen experiments, the channel blends education and entertainment, offering a fresh perspective on food culture. With personalities like Claire, Brad, and others, Bon Appétit helped reshape how we view cooking content on YouTube."
},
{
    id: 25,
    name: "Mark Rober",
    category: "Science",
    imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ_PUN6syZnswZL4YWqY_y2rXXl5w1eKGlQw&s",
    url: "https://www.youtube.com/user/MarkRober",
    instagram: "https://www.instagram.com/markrober/",
    twitter: "https://twitter.com/MarkRober",
    youtube: "https://www.youtube.com/user/MarkRober",
    tiktok: "https://www.tiktok.com/@markrober",
    description: "Mark Rober is a former NASA engineer turned YouTube sensation, known for blending science, engineering, and entertainment into viral hits. Whether he's building glitter bombs for package thieves or conducting large-scale experiments, Mark makes complex STEM concepts fun, accessible, and highly engaging. His videos are not just educational—they're engineered to inspire wonder and curiosity."
}
]